echo Starting Admin...
start cmd /k "cd admin && npm run dev"

echo Starting Frontend...
start cmd /k "cd frontend && npm run dev"

echo Starting Backend...
start cmd /k "cd backend && npm run dev"

echo Starting Python Recommendation...
start cmd /k "cd recommendation-service && uvicorn app:app --reload --port 8000"